version: "3.9"

volumes:
  mongo:
  redis:
  wildduck_webmail_node_modules:

services:
  # =========================
  # DATABASES
  # =========================
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - ./wildduck-webmail/.env
    ports:
      - "7001:27017"
    volumes:
      - ./wildduck-data/mongo:/data/db

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./wildduck-data/redis:/data

  # =========================
  # MAIL CORE
  # =========================
  wildduck:
    image: ghcr.io/zone-eu/wildduck:1.45.5
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "993:993"
      - "995:995"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./config/wildduck:/wildduck/config
      - ./certs:/wildduck/certs:ro

  # =========================
  # OUTBOUND MAIL (SMTP SUBMISSION)
  # =========================
  zonemta:
    image: ghcr.io/zone-eu/zonemta-wildduck:1.32.20
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "465:465"
      - "587:587"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./config/zone-mta:/app/config
      - ./zone-mta-plugins:/app/plugins:ro
      - ./certs:/app/certs:ro

  # =========================
  # SMTP INBOUND
  # =========================
  haraka:
    image: ghcr.io/zone-eu/haraka-plugin-wildduck:5.8.22
    restart: unless-stopped
    ports:
      - "25:25"
    depends_on:
      - mongo
      - redis
      - rspamd
    volumes:
      - ./config/haraka:/app/config
      - ./certs:/app/config/certs:ro

  # =========================
  # SPAM FILTER
  # =========================
  rspamd:
    image: nodemailer/rspamd
    restart: unless-stopped
    depends_on:
      - redis

  # =========================
  # WEBMAIL
  # =========================
  wildduck-webmail:
    build: "./wildduck-webmail"
    restart: unless-stopped
    command: sh -c "npm install && npm run bowerdeps -- --allow-root && node server.js --config=/app/config/default.toml"
    env_file:
      - ./wildduck-webmail/.env
    expose:
      - "3000"
    depends_on:
      - mongo
      - redis
      - wildduck
    volumes:
      - "./wildduck-webmail:/app"
      - ./config/wildduck-webmail:/app/config
      - wildduck_webmail_node_modules:/app/node_modules

  # =========================
  # CADDY (WEB)
  # =========================
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wildduck-webmail
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
