export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  BILLING_ADMIN: 'billing_admin',
  SUPPORT_ADMIN: 'support_admin',
  OPS_ADMIN: 'ops_admin',
  READ_ONLY_ADMIN: 'read_only_admin'
};

export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.BILLING_ADMIN]: 'Billing Admin',
  [ROLES.SUPPORT_ADMIN]: 'Support Admin',
  [ROLES.OPS_ADMIN]: 'Operations Admin',
  [ROLES.READ_ONLY_ADMIN]: 'Read Only'
};

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  CUSTOMERS_VIEW: 'customers:view',
  CUSTOMERS_EDIT: 'customers:edit',
  MARKETING_VIEW: 'marketing:view',
  MARKETING_EDIT: 'marketing:edit',
  BILLING_VIEW: 'billing:view',
  BILLING_EDIT: 'billing:edit',
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_EDIT: 'settings:edit',
  ADMINS_VIEW: 'admins:view',
  ADMINS_EDIT: 'admins:edit',
  AUDIT_VIEW: 'audit:view'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.BILLING_ADMIN]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.MARKETING_VIEW, PERMISSIONS.MARKETING_EDIT, PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_EDIT, PERMISSIONS.AUDIT_VIEW],
  [ROLES.SUPPORT_ADMIN]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_EDIT, PERMISSIONS.MARKETING_VIEW, PERMISSIONS.AUDIT_VIEW],
  [ROLES.OPS_ADMIN]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.MARKETING_VIEW, PERMISSIONS.MARKETING_EDIT, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT, PERMISSIONS.AUDIT_VIEW],
  [ROLES.READ_ONLY_ADMIN]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.MARKETING_VIEW, PERMISSIONS.BILLING_VIEW, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.ADMINS_VIEW, PERMISSIONS.AUDIT_VIEW]
};

export const getRolePermissions = role => ROLE_PERMISSIONS[role] || [];
export const hasPermission = (role, permission) => getRolePermissions(role).includes(permission);
