# Default TLS keys (can be overriden by individual services)
key="/wildduck/certs/yoover.com-key.pem"
#ca=["/wildduck/certs/ca.pem"]
cert="/wildduck/certs/yoover.com.pem"
#dhparam="/wildduck/certs/dhparam.pem"
